import Image from "next/image";
import Container from "@/components/ui/Container";
import BookingInquiryForm from "@/components/forms/BookingInquiryForm";
import { mealPlans, pricingDisclaimer, type Property } from "@/data/properties";

export default function CommercialStayDetail({ property }: { property: Property }) {
  return <main>
    <Container>
      <section className="relative overflow-hidden rounded-[2rem] bg-slate-900">
        <div className="relative min-h-[520px]"><Image src={property.imageUrl} alt={`${property.title}, a pet-friendly stay in ${property.location}`} fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/35 to-black/10" /></div>
        <div className="absolute inset-x-0 bottom-0 p-6 text-white sm:p-10 lg:p-14"><p className="text-xs font-semibold uppercase tracking-[.22em] text-white/75">{property.location}</p><h1 className="mt-3 max-w-4xl font-['Libre_Baskerville'] text-4xl font-semibold sm:text-5xl lg:text-6xl">{property.title}</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-white/85">{property.description}</p><div className="mt-6 flex flex-wrap items-center gap-3"><a href="#booking" className="inline-flex min-h-12 items-center rounded-full bg-[#d4a373] px-6 text-center font-semibold text-slate-950">Check Availability &amp; Get Exact Quote</a><span className="rounded-full border border-white/30 bg-white/10 px-4 py-3 text-sm font-semibold backdrop-blur">{property.petPolicy.allowed === "yes" ? "Pets complimentary" : "Pet policy to be confirmed"}</span></div></div>
      </section>

      <section className="grid gap-6 py-10 lg:grid-cols-[1.1fr_.9fr]">
        <div className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">{property.rateCard ? "Documented baseline rates" : "Starting from"}</p>{property.rateCard ? <div className="mt-4 grid grid-cols-3 gap-3"><div><p className="text-xs text-slate-500">Weekday</p><p className="mt-1 text-xl font-bold text-slate-900">INR {property.rateCard.weekday.toLocaleString("en-IN")}</p></div><div><p className="text-xs text-slate-500">Weekend</p><p className="mt-1 text-xl font-bold text-slate-900">INR {property.rateCard.weekend.toLocaleString("en-IN")}</p></div><div><p className="text-xs text-slate-500">Long weekend</p><p className="mt-1 text-xl font-bold text-slate-900">INR {property.rateCard.longWeekend.toLocaleString("en-IN")}</p></div></div> : <p className="mt-2 text-4xl font-bold text-slate-900">₹{property.pricePerNight.toLocaleString("en-IN")}<span className="text-lg font-medium text-slate-500">/night</span></p>}<p className="mt-4 font-medium text-slate-700">{property.rateCard ? `${property.rateCard.advancePercent}% advance documented` : `Base: ${property.baseUnit}`}</p><p className="mt-5 text-sm leading-6 text-amber-900">{property.rateCard?.reconfirmationRequired ? "Rates are historical or currently unverified. Reconfirm the current tariff before booking or payment." : pricingDisclaimer}</p></div>
        <div className="rounded-[1.75rem] bg-primary p-6 text-white shadow-sm sm:p-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-white/70">Verification status</p><h2 className="mt-2 font-['Libre_Baskerville'] text-3xl font-semibold">{property.verification.status === "verified" ? "Verified property details" : "Reconfirmation required"}</h2><p className="mt-3 text-white/85">Evidence: {property.verification.evidenceSource}. Date: {property.verification.verificationDate ?? "Not recorded"}.</p></div>
      </section>

      <section className="grid gap-8 py-8 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Flexible booking</p><h2 className="mt-2 font-['Libre_Baskerville'] text-3xl font-semibold text-slate-900">Booking units &amp; capacity</h2><div className="mt-6 grid gap-3">{property.bookingUnits.map((unit) => <div key={unit.name} className="flex items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5"><strong>{unit.name}</strong><span className="text-sm text-slate-600">{unit.capacity}</span></div>)}</div></div><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Confirmed details</p><h2 className="mt-2 font-['Libre_Baskerville'] text-3xl font-semibold text-slate-900">Stay highlights</h2><ul className="mt-6 space-y-3">{property.highlights.map((highlight) => <li key={highlight} className="flex gap-3 rounded-2xl bg-white p-4 text-slate-700"><span aria-hidden="true" className="text-primary">✓</span>{highlight}</li>)}</ul></div></section>
       <section className="grid gap-8 py-8 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Booking information</p><h2 className="mt-2 font-['Libre_Baskerville'] text-3xl font-semibold text-slate-900">Unit and capacity</h2><div className="mt-6 grid gap-3">{property.bookingUnits.map((unit) => <div key={unit.name} className="flex items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5"><strong>{unit.name}</strong><span className="text-sm text-slate-600">{unit.capacity}</span></div>)}</div></div><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Documented details</p><h2 className="mt-2 font-['Libre_Baskerville'] text-3xl font-semibold text-slate-900">What we can state</h2><ul className="mt-6 space-y-3">{property.highlights.map((highlight) => <li key={highlight} className="flex gap-3 rounded-2xl bg-white p-4 text-slate-700"><span aria-hidden="true" className="text-primary">✓</span>{highlight}</li>)}</ul><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><strong>Unconfirmed before booking:</strong> {property.verification.unconfirmedFields.join(", ")}.</div></div></section>

      <section className="my-10 rounded-[2rem] border border-[#e9dccb] bg-[#f5f1eb] p-6 sm:p-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Meal plans</p><h2 className="mt-2 font-['Libre_Baskerville'] text-3xl font-semibold text-slate-900">Choose the plan that suits your trip</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{mealPlans.map((plan) => <div key={plan.code} className="rounded-2xl bg-white p-5"><strong className="text-xl text-primary">{plan.code}</strong><p className="mt-2 text-sm leading-6 text-slate-600">{plan.label}</p></div>)}</div></section>

      <section className="py-10"><h2 className="font-['Libre_Baskerville'] text-3xl font-semibold text-slate-900">A closer look</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{property.gallery.slice(0,6).map((src, index) => <div key={src} className="relative aspect-[4/3] overflow-hidden rounded-2xl"><Image src={src} alt={`${property.title} property view ${index + 1}`} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover" /></div>)}</div></section>

      <section id="booking" className="my-12 scroll-mt-24 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-[0_25px_70px_-40px_rgba(15,76,92,.55)] sm:p-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Petstaycation enquiry</p><h2 className="mt-2 font-['Libre_Baskerville'] text-3xl font-semibold text-slate-900">Check Availability &amp; Get Exact Quote</h2><p className="mt-3 max-w-3xl leading-7 text-slate-600">Share your dates, group and pet details. Our team will check availability, reconfirm the property information and provide the exact tariff.</p><div className="mt-8"><BookingInquiryForm stayTitle={property.title} /></div></section>
    </Container>
    <div className="fixed inset-x-4 bottom-4 z-40 flex items-center justify-between gap-3 rounded-full bg-slate-900 p-2 pl-5 text-white shadow-2xl lg:hidden"><div className="min-w-0"><p className="truncate text-xs font-semibold">Starting from INR {property.pricePerNight.toLocaleString("en-IN")}/night</p><p className="text-[10px] text-white/65">{property.petPolicy.allowed === "yes" ? "Pets complimentary" : "Pet policy to be confirmed"}</p></div><a href="#booking" className="shrink-0 rounded-full bg-[#d4a373] px-4 py-3 text-xs font-bold text-slate-950">Check availability</a></div>
  </main>;
}
