import Image from "next/image";
import { maruRetreat as d } from "@/data/maruRetreat";
import MaruRetreatEnquiry from "./MaruRetreatEnquiry";

const wa = `https://wa.me/${d.commercial.whatsappNumber}?text=${encodeURIComponent("Hello, I would like to enquire about Maru Retreat Farmstay through Petstaycation.")}`;

function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) {
  return <p className={`mb-4 text-[11px] font-semibold uppercase tracking-[.24em] ${light ? "text-[#e8c49f]" : "text-[#8a4f3d]"}`}>{children}</p>;
}

function Heading({ children, light = false }: { children: React.ReactNode; light?: boolean }) {
  return <h2 className={`font-['Libre_Baskerville'] text-3xl leading-tight sm:text-4xl lg:text-5xl ${light ? "text-white" : "text-[#2f2824]"}`}>{children}</h2>;
}

export default function MaruRetreatDetail() {
  return <article className="overflow-x-hidden bg-[#f7f1e6] text-[#4a4039]">
    <section className="relative min-h-[760px] overflow-hidden">
      <Image src={d.images[0].src} alt={d.images[0].alt} fill priority sizes="100vw" className="object-cover" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(31,27,23,.88),rgba(31,27,23,.46)_58%,rgba(31,27,23,.12))]" />
      <div className="relative mx-auto flex min-h-[760px] max-w-7xl items-end px-5 pb-20 pt-28 sm:px-8 lg:px-10">
        <div className="max-w-3xl"><span className="rounded-full bg-[#987548] px-4 py-2 text-[10px] font-bold uppercase tracking-[.18em] text-white">{d.editorialBadge}</span><p className="mt-7 text-xs uppercase tracking-[.22em] text-[#f1d5b3]">Countryside Rajasthan · Exact location shared after booking</p><h1 className="mt-5 font-['Libre_Baskerville'] text-5xl leading-[1.02] text-white sm:text-6xl lg:text-7xl">Maru Retreat<br />Farmstay</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/85">Private plunge-pool villas, restful bedrooms, farm surroundings and space for travellers who bring their pets along.</p><div className="mt-7 flex flex-wrap gap-2">{["Pet friendly","Private pools","Two bedrooms","Attached bathrooms","Farm dining"].map(x => <span key={x} className="rounded-full border border-white/25 bg-black/15 px-4 py-2 text-xs text-white">{x}</span>)}</div><div className="mt-9 flex flex-wrap gap-3"><a href="#enquire" className="rounded-full bg-[#d6ae7f] px-6 py-3.5 text-sm font-bold text-[#2f2824]">Check availability</a><a href={wa} className="rounded-full border border-white/35 bg-white/10 px-6 py-3.5 text-sm font-bold text-white">WhatsApp us</a></div></div>
      </div>
    </section>

    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[1.05fr_.95fr] lg:px-10"><div><Eyebrow>A private countryside escape</Eyebrow><Heading>Quiet, comfortable and made for time together.</Heading><p className="mt-7 text-lg leading-8 text-[#665950]">A small, low-density retreat where earth-finished interiors, private pools and open farm spaces create a relaxed stay for couples, families, small groups and pet parents.</p></div><div className="grid grid-cols-2 gap-3">{["2 private villas","2 attached bathrooms","Private plunge pools","Pet-friendly lawns"].map((x,i)=><div key={x} className="rounded-[1.75rem] border border-[#d9c7b1] bg-white/65 p-6"><strong className="font-['Libre_Baskerville'] text-3xl text-[#8a4f3d]">0{i+1}</strong><p className="mt-3 text-sm">{x}</p></div>)}</div></section>

    <section className="bg-[#342d28] py-20 text-white sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><Eyebrow light>Bedrooms first</Eyebrow><Heading light>See where you will sleep.</Heading><p className="mt-5 max-w-2xl leading-7 text-white/65">The bedroom and bathroom arrangement is confirmed with your availability proposal, so you know exactly what suits your group before paying.</p><div className="mt-12 grid gap-5 lg:grid-cols-2">{d.rooms.map((room,i)=><article key={room.slug} className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.055]"><div className="relative h-96"><Image src={d.images[i+1].src} alt={d.images[i+1].alt} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" /></div><div className="p-7"><p className="text-xs uppercase tracking-[.18em] text-[#ddb58a]">{room.descriptor}</p><h3 className="mt-3 font-['Libre_Baskerville'] text-3xl">{room.name}</h3><p className="mt-4 leading-7 text-white/65">{room.description}</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><p className="rounded-xl bg-white/5 p-4">{room.bed}</p><p className="rounded-xl bg-white/5 p-4">Attached bathroom</p></div></div></article>)}</div></div></section>

    <section className="mx-auto grid max-w-7xl gap-5 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-2 lg:px-10"><div className="relative min-h-[520px] overflow-hidden rounded-[2.2rem]"><Image src={d.images[6].src} alt={d.images[6].alt} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" /></div><div className="rounded-[2.2rem] bg-[#4e5e43] p-8 text-white sm:p-12"><Eyebrow light>Pets belong here</Eyebrow><Heading light>Space to sniff, play and settle in.</Heading><p className="mt-7 text-lg leading-8 text-white/75">Dogs and other companion animals are welcome. Open-air time, lawn play and quiet villa stays make this a holiday the whole family can share.</p><div className="mt-8 flex flex-wrap gap-2">{["Dogs welcome","Open lawn","Farm walks","Pet details planned in advance"].map(x=><span key={x} className="rounded-full border border-white/20 px-4 py-2 text-xs">{x}</span>)}</div></div></section>

    <section className="bg-[#e8d9c3] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><Eyebrow>Property gallery</Eyebrow><Heading>Rooms, pool and places to unwind.</Heading><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{d.images.slice(1).map((im,i)=><figure key={im.src} className={`relative overflow-hidden rounded-[1.5rem] ${i<2?"min-h-[420px]":"min-h-72"}`}><Image src={im.src} alt={im.alt} fill sizes="(max-width:768px) 100vw, 33vw" className="object-cover" /><figcaption className="absolute bottom-3 left-3 rounded-full bg-black/50 px-3 py-1.5 text-[10px] uppercase tracking-[.14em] text-white">{im.category}</figcaption></figure>)}</div></div></section>

    <section className="mx-auto max-w-4xl px-5 py-20 sm:px-8 sm:py-28"><Eyebrow>Good to know</Eyebrow><Heading>Helpful details without revealing the property.</Heading><p className="mt-5 leading-7 text-[#706159]">For guest and partner privacy, the exact address, map pin and supplier identity are shared only after a booking is confirmed through Petstaycation.</p><div className="mt-10 divide-y divide-[#d8c6b0] border-y border-[#d8c6b0]">{d.faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none justify-between gap-5 font-semibold">{q}<span className="text-[#8a4f3d] group-open:rotate-45">+</span></summary><p className="pt-4 leading-7 text-[#706159]">{a}</p></details>)}</div></section>

    <section id="enquire" className="bg-[#342d28] px-5 py-20 text-white sm:px-8 sm:py-28"><div className="mx-auto grid max-w-6xl overflow-hidden rounded-[2.5rem] bg-[#eadbc7] text-[#4a4039] lg:grid-cols-[.7fr_1.3fr]"><div className="bg-[#8a4f3d] p-8 text-white sm:p-12"><Eyebrow light>Book with Petstaycation</Eyebrow><Heading light>Tell us who is travelling.</Heading><p className="mt-6 leading-8 text-white/75">Share dates, guest count and pet details. We will confirm the suitable villa, inclusions and final price directly.</p></div><div className="p-8 sm:p-12"><MaruRetreatEnquiry whatsappNumber={d.commercial.whatsappNumber} /></div></div></section>
  </article>;
}
