"use client";
import { FormEvent, useMemo, useState } from "react";

const initial = { checkIn:"", checkOut:"", adults:"2", children:"0", villa:"Either villa", pets:"1", petType:"Dog", breed:"", weight:"", age:"", vaccinated:"", behaviour:"", meals:"", experiences:"", name:"", phone:"", email:"", contact:"WhatsApp" };
export default function MaruRetreatEnquiry({ whatsappNumber }: { whatsappNumber: string }) {
  const [form,setForm]=useState(initial); const [errors,setErrors]=useState<Record<string,string>>({});
  const minDate=useMemo(()=>new Date().toISOString().slice(0,10),[]);
  const update=(key:keyof typeof initial,value:string)=>setForm(v=>({...v,[key]:value}));
  const track=(event:string)=>window.dispatchEvent(new CustomEvent("petstaycation:analytics",{detail:{event,property:"marubhoomi-farmstay-pushkar"}}));
  function submit(e:FormEvent){e.preventDefault(); const next:Record<string,string>={}; if(!form.checkIn)next.checkIn="Select check-in."; if(!form.checkOut||form.checkOut<=form.checkIn)next.checkOut="Choose a check-out after check-in."; if(!form.name.trim())next.name="Enter your name."; if(!form.phone.trim())next.phone="Enter a phone number."; if(form.email&&!/^\S+@\S+\.\S+$/.test(form.email))next.email="Enter a valid email."; if(Number(form.pets)>0&&!form.breed.trim())next.breed="Tell us the breed or type."; setErrors(next); if(Object.keys(next).length){track("enquiry_form_error");return;} const message=["Hello, I would like to enquire about Marubhoomi Farmstay Pushkar through Petstaycation.","",`Check-in: ${form.checkIn}`,`Check-out: ${form.checkOut}`,`Adults: ${form.adults}`,`Children: ${form.children}`,`Villa preference: ${form.villa}`,`Number of pets: ${form.pets}`,`Pet type: ${form.petType}`,`Breed: ${form.breed}`,`Approximate pet weight: ${form.weight||"Not provided"}`,`Pet age: ${form.age||"Not provided"}`,`Vaccination status: ${form.vaccinated||"Not provided"}`,`Behaviour around animals: ${form.behaviour||"Not provided"}`,`Meal preference: ${form.meals||"Not provided"}`,`Experiences interested in: ${form.experiences||"Not provided"}`,`Guest name: ${form.name}`,`Phone: ${form.phone}`,`Email: ${form.email||"Not provided"}`,`Preferred contact: ${form.contact}`].join("\n"); track("enquiry_form_submit"); window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer"); }
  const cls="mt-2 min-h-12 w-full rounded-xl border border-[#cfbda6] bg-white px-4 text-sm outline-none focus:border-[#8a4f3d] focus:ring-2 focus:ring-[#8a4f3d]/15";
  const field=(key:keyof typeof initial,label:string,type="text")=><label className="text-sm font-medium">{label}<input type={type} value={form[key]} min={type==="date"?minDate:undefined} onChange={e=>update(key,e.target.value)} className={cls}/>{errors[key]&&<span className="mt-1 block text-xs text-red-700">{errors[key]}</span>}</label>;
  return <form onSubmit={submit} onFocus={()=>track("enquiry_form_start")} noValidate className="grid gap-5 sm:grid-cols-2">
    {field("checkIn","Check-in","date")}{field("checkOut","Check-out","date")}{field("adults","Adults","number")}{field("children","Children","number")}
    <label className="text-sm font-medium">Villa preference<select value={form.villa} onChange={e=>update("villa",e.target.value)} className={cls}><option>Either villa</option><option>Maru Ratna</option><option>Maru Rasa</option><option>Both villas</option></select></label>{field("pets","Number of pets","number")}
    <label className="text-sm font-medium">Pet type<select value={form.petType} onChange={e=>update("petType",e.target.value)} className={cls}><option>Dog</option><option>Cat</option><option>Other companion animal</option></select></label>{field("breed","Breed / type")}{field("weight","Approximate weight")}{field("age","Pet age")}
    <label className="text-sm font-medium">Vaccination status<select value={form.vaccinated} onChange={e=>update("vaccinated",e.target.value)} className={cls}><option value="">Select</option><option>Up to date</option><option>Partially vaccinated</option><option>Discuss with us</option></select></label>{field("behaviour","Behaviour around animals")}{field("meals","Meal preference")}{field("experiences","Experiences interested in")}{field("name","Guest name")}{field("phone","Phone","tel")}{field("email","Email","email")}
    <label className="text-sm font-medium">Preferred contact<select value={form.contact} onChange={e=>update("contact",e.target.value)} className={cls}><option>WhatsApp</option><option>Phone</option><option>Email</option></select></label>
    <button className="min-h-12 rounded-full bg-[#8a4f3d] px-6 font-semibold text-white hover:bg-[#713e30] sm:col-span-2">Send availability enquiry on WhatsApp</button>
  </form>;
}
