import Image from "next/image";
import RedStoneFortEnquiry from "./RedStoneFortEnquiry";
import RedStoneFortGallery from "./RedStoneFortGallery";
import { formatExperiencePrice, redStoneFort } from "@/data/redStoneFort";

const d = redStoneFort;
const hero = d.images[0];

function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) {
  return <p className={`mb-4 text-[11px] font-semibold uppercase tracking-[.27em] ${light ? "text-[#e6bf91]" : "text-[#a25536]"}`}>{children}</p>;
}

function Heading({ children, light = false }: { children: React.ReactNode; light?: boolean }) {
  return <h2 className={`font-['Libre_Baskerville'] text-3xl leading-[1.2] sm:text-4xl lg:text-5xl ${light ? "text-[#fff9f0]" : "text-[#3b251b]"}`}>{children}</h2>;
}


export default function RedStoneFortDetail() {
  return (
    <article className="w-full overflow-x-clip bg-[#f4eee5] pb-24 text-[#4b3c34] lg:pb-0">
      <section className="relative min-h-[760px] overflow-hidden sm:min-h-[820px]">
        <Image src={hero.src} alt={hero.alt} fill priority sizes="100vw" className="object-cover" />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(35,20,15,.9)_0%,rgba(35,20,15,.62)_46%,rgba(35,20,15,.15)_100%)]" />
        <div className="relative mx-auto flex min-h-[760px] max-w-7xl items-end px-5 pb-16 pt-28 sm:min-h-[820px] sm:px-8 sm:pb-24 lg:px-10">
          <div className="min-w-0 w-full max-w-3xl animate-[fadeIn_.7s_ease-out]">
            <p className="text-[10px] font-semibold uppercase tracking-[.25em] text-[#edc99d] sm:text-xs">Jodhpur countryside · Rajasthan</p>
            <h1 className="mt-6 font-['Libre_Baskerville'] text-[2.8rem] leading-[1.03] text-white sm:text-6xl lg:text-7xl"><span className="block sm:inline">The Red</span><span className="block sm:inline"> Stone Fort</span></h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-white/82 sm:text-xl">An intimate pet-friendly heritage homestay shaped by red sandstone, rural landscapes and personal hospitality.</p>
            <div className="mt-7 flex flex-wrap gap-2 text-xs text-white"><span className="rounded-full border border-white/25 bg-white/10 px-4 py-2 backdrop-blur">Four guestrooms</span><span className="rounded-full border border-white/25 bg-white/10 px-4 py-2 backdrop-blur">Swimming pool</span><span className="rounded-full border border-white/25 bg-white/10 px-4 py-2 backdrop-blur">Pet friendly</span><span className="rounded-full border border-white/25 bg-white/10 px-4 py-2 backdrop-blur">~55 km from Jodhpur</span></div>
            <div className="mt-9 flex flex-wrap gap-3"><a href="#enquire" className="rounded-full bg-[#d9a56f] px-6 py-3.5 text-sm font-semibold text-[#2c1d17] transition hover:-translate-y-0.5 hover:bg-[#e7bb8d]">Check availability</a><a href={`https://wa.me/${d.commercial.whatsappNumber}?text=${encodeURIComponent("Hello, I would like to enquire about The Red Stone Fort.")}`} className="rounded-full border border-white/35 bg-white/10 px-6 py-3.5 text-sm font-semibold text-white backdrop-blur transition hover:bg-white/20">Enquire on WhatsApp</a></div>
          </div>
        </div>
      </section>

      <nav aria-label="Property sections" className="sticky top-0 z-30 hidden border-b border-[#d6c8ba] bg-[#f4eee5]/95 backdrop-blur lg:block"><div className="mx-auto flex max-w-7xl gap-8 px-10 py-4 text-[10px] font-semibold uppercase tracking-[.18em] text-[#694a3b]"><a href="#story">Heritage</a><a href="#rooms">Rooms</a><a href="#grounds">Pool & gardens</a><a href="#experiences">Experiences</a><a href="#pets">Pet policy</a><a href="#location">Location</a><a href="#enquire">Enquire</a></div></nav>

      <section id="story" className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[1.15fr_.85fr] lg:px-10">
        <div><Eyebrow>Beyond the pace of Jodhpur</Eyebrow><Heading>A quieter encounter with Rajasthan.</Heading><p className="mt-7 text-lg leading-8 text-[#65564d]">The approximately one-acre fortified residence carries architectural layers dating back around eight centuries, while its present family history begins in 1835. Today, four spacious guestrooms open onto a garden-facing veranda, accompanied by two gardens, a swimming pool, a dining room and relaxed common spaces.</p><p className="mt-5 leading-8 text-[#79695f]">Days can move between village walks, artisan visits, countryside drives, cooking sessions and long meals prepared around guest preferences. Pets are welcome, making the property a distinctive rural escape for travellers who prefer not to leave a family member behind.</p></div>
        <div className="grid grid-cols-2 gap-3 self-end">{[["~800","years of architectural antiquity"],["1835","present documented history"],["4","guestrooms"],["2","gardens"]].map(([value,label]) => <div key={label} className="rounded-[1.75rem] border border-[#d6c6b7] bg-white/55 p-6 shadow-[0_22px_50px_-38px_rgba(70,41,27,.5)]"><strong className="font-['Libre_Baskerville'] text-3xl text-[#7c3f28]">{value}</strong><p className="mt-3 text-[10px] uppercase leading-5 tracking-[.16em] text-[#806e63]">{label}</p></div>)}</div>
      </section>

      <section className="bg-[#38241b] py-20 text-[#eaded2] sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div className="self-center"><Eyebrow light>The heritage story</Eyebrow><Heading light>Eight Centuries of Architecture. A More Personal Way to Stay.</Heading><p className="mt-7 leading-8 text-white/65">The fortified site carries architectural layers dating back approximately eight centuries. Its present family history begins in 1835, when Thakur Bhabhoot Singh of Pokharan was granted the jagir of Dunara and restored the imposing entrance that continues to define the residence today.</p><p className="mt-5 leading-8 text-white/65">The estate has since evolved into an intimate four-room heritage homestay, preserving the scale and atmosphere of rural Rajasthan while adding the practical comforts expected by modern travellers.</p></div><div className="relative min-h-[520px] overflow-hidden rounded-[2.25rem]"><Image src={d.images[1].src} alt={d.images[1].alt} fill sizes="(max-width:1024px) 100vw, 60vw" className="object-cover" /></div></div></section>

      <section id="rooms" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><Eyebrow>Accommodation</Eyebrow><Heading>Four Rooms, Deliberately Intimate</Heading><p className="mt-7 text-lg leading-8 text-[#65564d]">Each of the four approximately 240 sq. ft. guestrooms combines generous proportions with practical modern comfort. Rooms include a sitting area, wardrobe storage and a private ensuite bathroom fitted with Jaquar fixtures.</p><p className="mt-5 leading-8 text-[#79695f]">Each room opens onto a broad veranda overlooking the garden, creating an easy transition between the private room and the quiet outdoor spaces.</p></div><div className="grid grid-cols-2 gap-x-7">{d.roomAmenities.map((amenity) => <div key={amenity} className="border-b border-[#d8cabc] py-3.5 text-sm">✓ {amenity}</div>)}</div></div></section>

      <section id="grounds" className="border-y border-[#d6c7b9] bg-[#e8ddd0] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-4 lg:grid-cols-2"><div className="relative min-h-[520px] overflow-hidden rounded-[2.25rem]"><Image src={d.images[4].src} alt={d.images[4].alt} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" /></div><div className="grid gap-4"><div className="rounded-[2.25rem] bg-[#7b412a] p-8 text-white sm:p-10"><Eyebrow light>Pool & open spaces</Eyebrow><h3 className="font-['Libre_Baskerville'] text-3xl">Slow Afternoons by the Pool</h3><p className="mt-5 leading-8 text-white/70">The outdoor swimming pool is framed by a generous deck and relaxed seating, offering a private-feeling space for unhurried afternoons between village explorations and long meals.</p><p className="mt-4 text-xs text-white/50">A verified pool photograph was not present in the accessed Dropbox subset; no substitute image is shown.</p></div><div className="rounded-[2.25rem] border border-[#cdbbab] bg-[#f7f1e9] p-8 sm:p-10"><h3 className="font-['Libre_Baskerville'] text-2xl text-[#3d281f]">Beyond the guestrooms</h3><p className="mt-4 leading-7 text-[#746359]">Two gardens, a broad veranda, a dining room, multiple common spaces and poolside seating give a small group room to find its own rhythm—morning tea outdoors, reading in the shade or quiet conversation after dinner.</p></div></div></div></div></section>

      <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-2 lg:px-10"><div><Eyebrow>Dining</Eyebrow><Heading>Freshly Prepared, Personally Served</Heading><p className="mt-7 text-lg leading-8 text-[#65564d]">Meals are prepared fresh and can be adapted to the preferences of resident guests. Indian cuisine forms the core of the kitchen, complemented by a limited selection of Chinese and Italian dishes.</p><p className="mt-5 leading-8 text-[#79695f]">The dining experience is personal and unhurried, consistent with the character of a small hosted homestay. Meal plans and charges are confirmed with the room proposal.</p></div><div className="relative min-h-[440px] overflow-hidden rounded-[2.25rem]"><Image src={d.images[5].src} alt={d.images[5].alt} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" /></div></section>

      <section id="experiences" className="bg-[#31221b] py-20 text-white sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><Eyebrow light>Hosted journeys</Eyebrow><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><Heading light>Step Beyond the Fort Walls</Heading><p className="max-w-lg leading-7 text-white/60">Experiences are subject to availability and advance confirmation. Prices may change.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{d.experiences.map((experience,index) => <article key={experience.id} className="group rounded-[2rem] border border-white/10 bg-white/[.055] p-7 transition hover:-translate-y-1 hover:border-[#d9a56f]/45" data-experience={experience.id}><div className="flex items-center justify-between gap-4"><span className="text-[10px] tracking-[.2em] text-[#d9a56f]">0{index+1}</span><span className="rounded-full bg-[#d9a56f]/10 px-3 py-1.5 text-xs font-semibold text-[#edc99d]">{formatExperiencePrice(experience)}</span></div><h3 className="mt-7 font-['Libre_Baskerville'] text-xl">{experience.title}</h3><p className="mt-4 leading-7 text-white/60">{experience.description}</p></article>)}</div></div></section>

      <section id="pets" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="grid gap-12 lg:grid-cols-[1fr_1fr]"><div><Eyebrow>Owner-confirmed pet friendly</Eyebrow><Heading>Rajasthan, Without Leaving Your Pet Behind</Heading><p className="mt-7 text-lg leading-8 text-[#65564d]">The Red Stone Fort welcomes guests travelling with pets, allowing families to experience rural Rajasthan without leaving their companions behind. The gardens, veranda and quiet surroundings provide a more relaxed setting than a conventional city hotel.</p><p className="mt-5 leading-8 text-[#79695f]">{d.petPolicy.notes}</p></div><div className="rounded-[2.25rem] border border-[#d3c2b2] bg-white/55 p-7 sm:p-9"><h3 className="font-['Libre_Baskerville'] text-2xl text-[#482d21]">Pet policy at a glance</h3><dl className="mt-7 divide-y divide-[#ddd0c4] text-sm">{[["Pets allowed","Yes"],["Permitted pet types",d.petPolicy.permittedTypes],["Maximum pets per room",d.petPolicy.maximumPets],["Pet fee",d.petPolicy.fee],["Security deposit",d.petPolicy.securityDeposit],["Leash requirements",d.petPolicy.leashRequirements],["Dining-area access",d.petPolicy.diningAccess],["Pool-area access",d.petPolicy.poolAccess],["Vaccination records",d.petPolicy.vaccinationRecords],["Damage & cleaning",d.petPolicy.damageCharges]].map(([term,value]) => <div key={term} className="grid grid-cols-[1fr_1.1fr] gap-5 py-3.5"><dt className="text-[#806e63]">{term}</dt><dd className="font-medium text-[#49362c]">{value}</dd></div>)}</dl></div></div></section>

      <section className="border-y border-[#d5c6b8] bg-[#e9ded2] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><Eyebrow>Original property photography</Eyebrow><Heading>The Residence, In Its Own Light</Heading><p className="mt-5 max-w-2xl leading-7 text-[#716057]">Genuine photographs from the supplied property library, locally optimised for the web.</p><div className="mt-10"><RedStoneFortGallery images={d.images} /></div></div></section>

      <section id="location" className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[1fr_1fr] lg:px-10"><div><Eyebrow>Jodhpur countryside</Eyebrow><Heading>Rural quiet, shared privately.</Heading><p className="mt-7 text-lg leading-8 text-[#65564d]">The stay is set in peaceful Rajasthan countryside within driving reach of Jodhpur. For partner and guest privacy, the exact address, route and transfer plan are shared only after a booking is confirmed through Petstaycation.</p><a href="#enquiry" className="mt-8 inline-flex rounded-full bg-[#7c3f28] px-6 py-3.5 text-sm font-semibold text-white">Ask about travel planning</a></div><div className="relative min-h-[460px] overflow-hidden rounded-[2.25rem]"><Image src={d.images[2].src} alt={d.images[2].alt} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" /></div></section>

      <section className="bg-[#3a251c] py-20 text-white sm:py-28"><div className="mx-auto max-w-4xl px-5 sm:px-8"><div className="text-center"><Eyebrow light>Before you arrive</Eyebrow><Heading light>Questions, answered clearly.</Heading></div><div className="mt-12 divide-y divide-white/10 border-y border-white/10">{d.faqs.map(([question,answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-semibold focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white"><span>{question}</span><span className="text-[#d9a56f] transition group-open:rotate-45">+</span></summary><p className="max-w-3xl pt-4 leading-7 text-white/62">{answer}</p></details>)}</div></div></section>

      <section id="enquire" className="bg-[#f4eee5] py-20 sm:py-28"><div className="mx-auto grid max-w-6xl overflow-hidden rounded-[2.5rem] border border-[#d5c4b5] bg-[#e8dbce] shadow-[0_35px_80px_-48px_rgba(67,39,26,.65)] lg:grid-cols-[.8fr_1.2fr]"><div className="bg-[#7c3f28] p-8 text-white sm:p-12"><Eyebrow light>Direct enquiry</Eyebrow><h2 className="font-['Libre_Baskerville'] text-3xl leading-tight sm:text-4xl">Leave the City Behind. Bring Your Pet Along.</h2><p className="mt-6 leading-8 text-white/68">Room tariffs are provided with availability. Share your dates, room requirement and pet details for a considered proposal from Petstaycation.</p><dl className="mt-9 space-y-4 text-sm"><div><dt className="text-white/50">Rooms</dt><dd className="mt-1">Four · approximately 240 sq. ft. each</dd></div><div><dt className="text-white/50">Check-in / check-out</dt><dd className="mt-1">{d.commercial.checkIn} / {d.commercial.checkOut}</dd></div><div><dt className="text-white/50">Room tariff</dt><dd className="mt-1">On request</dd></div></dl></div><div className="p-8 sm:p-12"><RedStoneFortEnquiry whatsappNumber={d.commercial.whatsappNumber} /></div></div></section>

      <div className="fixed bottom-4 left-4 z-40 flex w-[calc(100vw-2rem)] max-w-[22.5rem] items-center justify-between gap-3 rounded-full border border-white/10 bg-[#38241b]/95 p-2 pl-5 text-white shadow-2xl backdrop-blur lg:hidden"><div className="min-w-0"><p className="text-[9px] uppercase tracking-[.14em] text-white/50">Tariff on request</p><p className="truncate text-xs font-semibold">The Red Stone Fort</p></div><a href="#enquire" className="shrink-0 rounded-full bg-[#d9a56f] px-4 py-3 text-sm font-semibold text-[#2c1d17]">Check availability</a></div>
    </article>
  );
}
